### PR TITLE
Post commenting, RFC

### PR DESCRIPTION
**Pull request by stiggg**
I'll try to set up installation soon so comment functionality can be seen in action... Don't merge yet :)

### CODE REVIEW

**Comment by artur-gajewski** [comment]
I checked out the PR and quite like it. I even liked the styling, fits perfectly with the site. If you don't have any second thoughts I would merge this and release to php-updates.com asap.

**Comment by artur-gajewski** [comment]
Actually, can you make it so that instead of displaying the user's username, display his/her real name?

**Comment by stiggg** [comment]
Ah ok, that's possible.

**Comment by stiggg** [comment]
Now I think I'm good with this. Artur, if you're happy, fire at will.

**Pull request merged**
