### PR TITLE
Bookmarklet

### PR DESCRIPTION
**Pull request by wysow**
Can save content from an url, refs #66

### CODE REVIEW

**Comment by artur-gajewski** [comment]
Pull your branch and tried to test it, but all I could see was a button "Cobase Bookmarklet" but pressing it didn't do anything. Can you provide info on how to test this?

**Comment by wysow** [comment]
Hello,

Sure this is the "bookmarklet" so you need to drag and drop it to your favorites bar in your browser.

Then when you are on a page that you want to save to Cobase all you need to do is click on this bookmarklet in your favorites bar ;)

One more thing I need to do is to avoid errors when trying to parse meta tags from a site which is private or that Cobase cannot reach, a commit with that wiil follow as soon as possible.

**Comment by wysow** [comment]
Also I will add a feature to allow the user to select only some text on the page that he/she wants to save to Cobase (it will save the text and the url of the current page)

**Comment by artur-gajewski** [comment]
I like this feature a lot, very useful. However, when I got the popover window with the form, the groups pulldown is empty even though there are groups created. Can you check this and when you get it fixed I will merge this.

**Comment by artur-gajewski** [comment]
And also, shouldn't the content for the "Share an update" have some content in it from the site or is the purpose to copy/paste from the page before clicking on the bookmarklet button?

Also, "Cobase Bookmarklet" would be better as "Bookmarklet" for the button text. ;-)

**Comment by artur-gajewski** [comment]
Also, the domain for the cobase seems to be hard coded to cobase.localhost.

**Comment by wysow** [comment]
So in this new commit no more hardcoded urls (I hope ;)), you can highlight some text on the current page to add content to the post in cobase. By default the bookmarklet parse the metadata of the url (title, description or facebook description if exists and facebook site name if exists.

If the current site is protected or there is a network problem when trying to get the metadata, a content "by default" is set to invite the user to set his own content.

For the groups pulldown empty, it is because it only shows groups the user is subscribed to, if you don't like this I can change to show all the groups by default.

On my computer the text for the button is already "Cobase bookmarklet", can you tell me more on this, maybe a screenshot could help me find the bug...

**Comment by artur-gajewski** [comment]
Can you make it so that the groups pulldown shows all groups in alphabetical order? This way user can share an update even to a group he/she is not subscribed to.

I meant if you could change the title of the button from "Cobase Bookmarklet" to "Bookmarklet" and perhaps add a tooltip to describe what to do. As I didn't know what a bookmarklet is, I tried to click on the button and nothing happened :D

**Comment by wysow** [comment]
All groups are now shown in the pulldown.

I have NOT change the title of the button because some users may have multiple bookmarklets in their favorites bar so they need to identify each one. Is it OK for you ?

**Comment by artur-gajewski** [comment]
Sounds good to me, will check out this PR when I get back to computer again. Thanks for your effort!

**Comment by artur-gajewski** [comment]
When saving new update from a bookmarklet, I get an exception:

PHP Fatal error:  Call to a member function getShortUrl() on a non-object in /workspace/cobase/src/Cobase/AppBundle/Controller/PostController.php on line 245

Reason for this is that you never attach a group entity to the post. Can you fix this as well and after this it seems like the PR is ok.

**Comment by wysow** [comment]
I think this is a regression when we decide to show all groups in the pulldown, I can manually attach the group no problem but the code is now less "proper" than the save of a normal post, do you understand me ?

On my computer now the content of the post is always empty, but if I revert to only show subscribed groups, everything works as expected... Not sure where the problem really is...

**Comment by artur-gajewski** [comment]
You can fix this by obtaining the entity of a group by it's ID from the request and then setting it to the post.

What comes to the content issue, I have not checked out your javascript yet. Do you think you would be able to fix the empty content issue?

**Comment by wysow** [comment]
Hello,

I think you don't understand me, what I want to say is that if we set the group pulldown to show only subscribed groups everything works fine (the save and the fetched content).

Maybe there is a security somewhere that do not allow creating a post in not subscribed groups ?

**Comment by artur-gajewski** [comment]
As far as the security goes, users are allowed to post into groups that they are not subscribed to. Subscriptions are only to list posts on front page from the subscribed groups.

Doesn't setting the content on the fancybox come from the javascript when the fancybox is opened?

**Comment by wysow** [comment]
I think it will be easier to talk about that on IRC, can you join me on #cobase ?

**Pull request merged**
